definitions:
  main.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  main.Movie:
    properties:
      description:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
info:
  title: Movie API
  version: 1.0.0
  contact: {}
paths:
  /movie:
    post:
      consumes:
      - application/json
      description: Creates a new movie entry.
      parameters:
      - description: Movie data
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/main.Movie'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Movie'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Create a new movie
  /movies:
    get:
      description: Get all the registered movies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Movie'
            type: array
      summary: Get all movies
swagger: "2.0"
